FROM node:20-slim AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/templates/default.conf.template
ENV BACKEND_URL=http://backend:3000
ENV NGINX_ENVSUBST_TEMPLATE_VARS=BACKEND_URL
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
